package qouteall.imm_ptl.core.compat.sodium_compatibility;

import net.caffeinemc.mods.sodium.client.render.chunk.async.CullTask;
import net.caffeinemc.mods.sodium.client.render.chunk.lists.DeferredTaskList;
import net.caffeinemc.mods.sodium.client.render.chunk.lists.SortedRenderLists;
import net.caffeinemc.mods.sodium.client.render.chunk.occlusion.CullType;
import net.caffeinemc.mods.sodium.client.render.chunk.occlusion.SectionTree;
import net.caffeinemc.mods.sodium.client.util.FogParameters;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.Nullable;
import org.joml.Matrix4f;
import org.joml.Vector3d;
import org.joml.Vector3dc;

import java.util.EnumMap;
import java.util.Map;

/**
 * C2-1 D1 — the WIDENED per-view Sodium rendering context (v2), replacing IP's 2-field
 * {@code SodiumRenderingContext} (renderLists + renderDistance). The class NAME is kept for facade
 * compatibility ({@code SodiumInterface.Invoker.createNewContext} returns it as {@code Object};
 * {@code IESodiumRenderSectionManager.ip_swapContext} takes it — both signatures unchanged).
 *
 * <p>Field set = THE FINAL D1 SWAP LIST of port-note {@code migration/port-notes/C2-sodium-iris.md}
 * §2 (verify-lens-1 approved), grounded field-by-field in the census
 * {@code migration/C2_0_CENSUS.md} "SWAP-SET CLASSIFICATION". Per-field justification is cited on
 * each field below. Everything NOT here is NEVER-SWAP world/build/GPU/timing infrastructure (census
 * :181-200 / :212-219) and stays on the live {@code RenderSectionManager} /
 * {@code SodiumWorldRenderer}.
 *
 * <p>Lifetime (design {@code migration/C2_DESIGN.md} §3.1.3; NOTE-6 corrected model —
 * TREE-PERSISTENCE WITH SYNCHRONOUS CONSUMPTION): contexts are PERSISTENT, held in
 * {@link SodiumContextRegistry} keyed by rendering-portal identity. Under the §4.1 mitigation (b)
 * no CullTask survives a swap (every pass blocking-consumes its own task before the swap-out);
 * what persists and converges across passes is the cull OUTPUT — the SectionTrees (via the
 * {@code cullResultsContent} content-swap) plus render tree/lists. A COLD context (all seeds
 * below) is legitimate: null renderTree/pendingTask/taskLists, empty renderLists — javap-proven
 * tolerated by every consumer (see per-field notes).
 */
public class SodiumRenderingContext {

    // ===== RenderSectionManager REFERENCE-SWAP set (census C2_0_CENSUS.md swap classification
    // "RenderSectionManager — SWAP"; javap: all non-final on 0.9.1, section (c) :91) ==============

    /**
     * Census :165. Per-view output list; regenerated by readRenderListFromTree/renderOutOfGraph,
     * consumed by the draw path (SWR.renderLayer → RSM.getRenderLists()). Seed =
     * {@code SortedRenderLists.empty()} — javap: returns the immutable static EMPTY singleton
     * (census CONFIRMATIONS :159), so the seed survives sharing across cold contexts.
     */
    public SortedRenderLists renderLists;

    /**
     * Census :166. Per-view current cull tree; set from findBestTree/renderOutOfGraph. Cold seed
     * null is legitimate: {@code RSM.isBoxVisible(DDDDDD)} returns true on null renderTree
     * (javap offsets 1-33), and readRenderListFromTree's findBestTree-null branch blocking-consumes
     * the same-pass cull (census (e) mechanism 3).
     */
    public @Nullable SectionTree renderTree;

    /**
     * Census :167 — THE pending-async-task field. Set in scheduleAsyncWork, cleared in
     * consumeCullTaskResults. Swapped for structural symmetry (NOTE-6: under mitigation (b) this
     * is always null on BOTH sides at swap time — no CullTask has cross-pass life). Seed null.
     * INVARIANT (race mitigation (b), port-note §4.1):
     * {@code ip_swapContext} drains the LIVE pendingTask via blocking
     * {@code consumeCullTaskResults(true)} BEFORE every swap, so this field is null in every
     * swapped-OUT context — no CullTask is ever outstanding while its context is parked here.
     */
    public @Nullable CullTask pendingTask;

    /**
     * Census :168. Set in consumeCullTaskResults / renderOutOfGraph; consumed by
     * updateChunks/submitDeferredSectionTasks (which null-guards — port-note §2). View-derived
     * deferred-build list; swapped so a portal view's deferred builds don't bleed into the outer
     * world's build submission. Seed null (guarded).
     */
    public @Nullable DeferredTaskList taskLists;

    /**
     * Census :169. Per-PASS counter incremented in prepareRender; captured by CullTask; basis of
     * cameraStableSince staleness and of the #3 ChunkRenderList.reset trigger. Swapped for
     * per-context staleness-bookkeeping coherence (the #3 trigger itself is NOT neutralised by
     * this — census correction 1; MixinSodiumRenderRegion ships unconditionally). Cold seed 0.
     */
    public int frame;

    /**
     * Census :170. Per-view render-list dirty flag (set by invalidateRenderLists, cleared in
     * finalizeRenderLists). Cold seed false — a fresh RSM starts false; the cold context's first
     * pass sets it via the cull landing / camera-changed chain.
     */
    public boolean needsRenderListUpdate;

    /**
     * Census :171. Set by notifyChangedCamera, consumed in prepareRender/finalizeRenderLists.
     * Cold seed false (fresh-RSM default): on the cold context's first pass the SWR-side
     * {@link #lastFogParameters} {@code FogParameters.NONE} seed forces the fogChanged comparison
     * true at setupTerrain (javap offsets 174-194) → notifyChangedCamera fires → this goes true —
     * exactly a fresh RSM's own first-frame behavior.
     */
    public boolean cameraChanged;

    /**
     * Census :172. Set to {@code frame} in notifyChangedCamera; gates LOCAL cull-tree acceptance
     * in consumeCullTaskResults ({@code cameraStableSince <= task.getFrame()}, javap offsets
     * 76-87). Cold seed 0 — every task accepted, correct for a fresh view.
     */
    public int cameraStableSince;

    /**
     * Census :173. Set in prepareFrame from the camera-position arg (javap prepareFrame offset
     * 0-2: unconditional putfield before any read in the pass). Cold seed null is safe: no
     * consumer runs before prepareFrame within a pass, and the only cross-pass reader
     * (isBoxVisible) reads renderTree, not cameraPosition.
     */
    public @Nullable Vector3dc cameraPosition;

    /**
     * Census :174. World-origin dirty flag consumed per-view (gates cull scheduling +
     * setupTerrain loop exit). Swapped per port-note §2; the "broadcast markGraphDirty to ALL
     * contexts" alternative is the ledgered live-round watch — the swap driver
     * ({@code OnSodiumPresent.switchContextWithCurrentWorldRenderer}) calls
     * {@code swr.scheduleTerrainUpdate()} (→ markGraphDirty) after every swap, so the swapped-IN
     * context always re-culls; a swapped-OUT context may carry a stale false across a world edit
     * until its next swap-in (accepted, watch item). Cold seed false (driver sets it true
     * immediately after swap-in).
     */
    public boolean needsGraphUpdate;

    /**
     * Census :175. {@code private final int} on 0.9.1 (javap section (c) :91) — swapped via
     * {@code @Shadow @Final @Mutable} on the mixin. Seeded from the facade's
     * {@code createNewContext(renderDistance)} arg; must never be 0 (validated at swap-in).
     * NOTE: NOT necessarily equal to options-effective render distance — IP's own
     * {@code PortalRenderer.getPortalRenderDistance} legitimately requests a reduced
     * (reducedPortalRendering) or enlarged (scale&gt;2 portal) distance; see the swap-in validate.
     */
    public int renderDistance;

    // ===== SodiumWorldRenderer camera-cache REFERENCE-SWAP five (census :202-209; without these
    // every portal pass sees a "camera moved" delta vs the outer camera and thrashes
    // notifyChangedCamera/invalidateRenderLists for BOTH views — census :210). Swapped by the
    // driver OnSodiumPresent.switchContextWithCurrentWorldRenderer via the IESodiumWorldRenderer
    // accessors. Do NOT swap SWR.renderDistance (port-note §4.3 — setupTerrain HEAD full-reload
    // thrash; javap offsets 21-39 compare it against Options.getEffectiveRenderDistance). ========

    /**
     * Census :205. Cold seed null — setupTerrain null-seeds it with the current camera pos
     * (javap offsets 123-132), sodium's own fresh-SWR behavior.
     */
    public @Nullable Vector3d lastCameraPos;

    /** Census :206. Rotation-changed basis. Cold seed 0. */
    public double lastCameraPitch;

    /** Census :207. Rotation-changed basis. Cold seed 0. */
    public double lastCameraYaw;

    /**
     * Census :208. Fog-cull-distance-changed basis. Cold seed {@code FogParameters.NONE} — the
     * SWR ctor's own seed (javap ctor offsets 5-8). MUST be non-null: setupTerrain calls
     * {@code lastFogParameters.cullDistance()} with NO null check (javap offsets 178-185 — a null
     * here is an NPE). The NONE-vs-real mismatch also usefully forces notifyChangedCamera on the
     * cold context's first pass.
     */
    public FogParameters lastFogParameters = FogParameters.NONE;

    /**
     * Census :209. Cull-matrix-changed basis; sodium updates it IN PLACE via Matrix4f.set (javap
     * offset 246-252), so each context owning its own instance is exactly right. Cold seed null —
     * setupTerrain null-seeds it with {@code new Matrix4f(cullMatrixArg)} (javap offsets 135-152).
     */
    public @Nullable Matrix4f cullMatrix;

    // ===== CONTENT-SWAP holders for the two FINAL RSM members (census :177-179 — cannot
    // reference-swap; ip_swapContext clears + repopulates the live containers) ==================

    /**
     * Census :178 — snapshot holder for {@code final Map<CullType,SectionTree> cullResults}
     * (an EnumMap in the RSM ctor, javap offsets 130-139). On swap: the live map's entries are
     * displaced into the outgoing context's holder and the incoming holder's entries repopulate
     * the live map. {@code SectionTree.isValidFor} gives partial cross-context protection on top.
     */
    public final Map<CullType, SectionTree> cullResultsContent = new EnumMap<>(CullType.class);

    /**
     * Census :179 — content holder for {@code final AsyncCameraTimingControl cameraTimingControl}
     * field {@code previousPosition}. Cold seed null = ACTC's own fresh state
     * (javap getShouldRenderSync offsets 5-18: null → seed + return TRUE), which makes a cold
     * context's first finalizeRenderLists take the SYNC path — same-pass convergence for free.
     */
    public @Nullable Vec3 timingPreviousPosition;

    /** Census :179 — content holder for ACTC {@code isSyncRendering}. Cold seed false (ACTC ctor). */
    public boolean timingIsSyncRendering;

    // ===== Registry bookkeeping (design §3.1.3; not part of the swap payload) ===================

    /**
     * The dimension whose RSM/world this context's trees/lists were built against. Set by
     * {@link SodiumContextRegistry} at acquire; used to invalidate the context when that
     * dimension's LevelRenderer is disposed/replaced or the portal's destination changes.
     */
    public @Nullable ResourceKey<Level> dimension;

    /**
     * The RSM whose displaced state this context currently holds (set after every swap by
     * {@code ip_swapContext}; weak — a strong ref would pin a dead RSM's whole region/GPU graph
     * from a registry-parked context). RSM-REPLACEMENT GUARD (C2-1 self-review catch): sodium's
     * {@code SWR.reload()} — fired at setupTerrain HEAD whenever
     * {@code Options.getEffectiveRenderDistance()} changed — runs {@code initRenderer()}, which
     * {@code deleteRendererState()}s and then constructs a NEW RenderSectionManager (javap
     * initRenderer offsets 1 / 68-84). For dest dims that reload fires INSIDE our swap bracket
     * (the dest setupTerrain only ever runs there), so the :424 restore would otherwise exchange
     * a DEAD RSM's state into the fresh instance. {@code ip_swapContext} compares this against
     * the live RSM and, on mismatch, {@code resetRsmSideToCold} first.
     */
    public @Nullable java.lang.ref.WeakReference<
        net.caffeinemc.mods.sodium.client.render.chunk.RenderSectionManager> swapPartnerRsm;

    public SodiumRenderingContext(int renderDistance) {
        this.renderDistance = renderDistance;
        this.renderLists = SortedRenderLists.empty();
    }

    /**
     * Resets the RSM-SIDE payload (+ the content holders for the two final RSM members) to the
     * cold seeds, adopting {@code liveRenderDistance} (the fresh RSM's own, already-correct
     * value) so the renderDistance exchange becomes a no-op. Deliberately does NOT touch the
     * SWR-side camera-cache five: the SodiumWorldRenderer instance SURVIVES reload() (only its
     * {@code renderSectionManager} field is replaced), so those values remain valid for their
     * SWR. Used only by the RSM-replacement guard — see {@link #swapPartnerRsm}.
     */
    public void resetRsmSideToCold(int liveRenderDistance) {
        this.renderLists = SortedRenderLists.empty();
        this.renderTree = null;
        this.pendingTask = null;
        this.taskLists = null;
        this.frame = 0;
        this.needsRenderListUpdate = false;
        this.cameraChanged = false;
        this.cameraStableSince = 0;
        this.cameraPosition = null;
        this.needsGraphUpdate = false;
        this.renderDistance = liveRenderDistance;
        this.cullResultsContent.clear();
        this.timingPreviousPosition = null;
        this.timingIsSyncRendering = false;
    }
}
