package qouteall.q_misc_util.my_util;

import com.mojang.datafixers.util.Pair;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.DoubleTag;
import net.minecraft.world.phys.Vec3;
import org.joml.Matrix4f;
import org.joml.Vector3f;
import org.joml.Vector4f;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * AUTHORED S2 migration payload — NOT a carried IP test file (IP's test tree contains only
 * Mesh2DTest/HelperTest). Invariant tests for the carved-in {@link DQuaternion}
 * (migration/EXECUTION_PLAN.md §3 S2(a) deliverable, hard constraint 8; D4.5 math harness —
 * the geometry-sign regression net, DEPENDENCY_ORDER §4.1 milestone 1).
 *
 * <p>Every expected value is hand-derived from first principles (derivations inline) —
 * never generated by calling the code under test. Quaternion equality is checked with a
 * comparator implemented HERE (double-cover-aware, independent of
 * {@code DQuaternion.distanceSq}, which has its own test below).
 *
 * <p>Conventions pinned (cross-reference: migration/port-notes/S02-qmiscutil.md §4.3–4.4 —
 * the mathB translator fragment was merged into that note at assembly time):
 * <ul>
 * <li>{@code a.hamiltonProduct(b)} = a⊗b = "firstly do b, then do a" (RIGHT operand first);
 *     {@code a.combine(b)} = b⊗a = "firstly a, then b".</li>
 * <li>{@code rotate(v)} = q ⊗ v ⊗ q̄ is the ACTIVE right-handed rotation.</li>
 * <li>JOML is COLUMN-form: {@code toMatrix()} columns are the rotated basis vectors and
 *     {@code M.transformDirection(v)} = M·v = {@code rotate(v)}; treating the matrix as
 *     row-form (transposing) yields the INVERSE rotation — the FrontClipping trap class
 *     (memory: the IP_DEVIATIONS row-vector note about JOML is WRONG).</li>
 * </ul>
 */
class DQuaternionTest {

    private static final double EPS = 1e-12;
    /** For values that pass through a float (Quaternionf/Matrix4f) round trip. */
    private static final double EPS_F = 1e-5;

    private static final double SIN45 = 0.7071067811865476; // sqrt(2)/2
    private static final double SIN22_5 = 0.3826834323650898;
    private static final double COS22_5 = 0.9238795325112867;

    private static void assertVec(Vec3 expected, Vec3 actual, double eps, String msg) {
        assertEquals(expected.x, actual.x, eps, msg + " (x); actual=" + actual);
        assertEquals(expected.y, actual.y, eps, msg + " (y); actual=" + actual);
        assertEquals(expected.z, actual.z, eps, msg + " (z); actual=" + actual);
    }

    /**
     * Double-cover-aware quaternion comparison implemented independently of the class
     * under test: q and -q represent the same rotation, so accept either sign.
     */
    private static void assertSameRotation(
        DQuaternion expected, DQuaternion actual, double eps, String msg
    ) {
        boolean plus = Math.abs(expected.x - actual.x) < eps
            && Math.abs(expected.y - actual.y) < eps
            && Math.abs(expected.z - actual.z) < eps
            && Math.abs(expected.w - actual.w) < eps;
        boolean minus = Math.abs(expected.x + actual.x) < eps
            && Math.abs(expected.y + actual.y) < eps
            && Math.abs(expected.z + actual.z) < eps
            && Math.abs(expected.w + actual.w) < eps;
        assertTrue(plus || minus,
            msg + " — expected ±" + expected + " but was " + actual);
    }

    private static void assertQuatComponents(
        double x, double y, double z, double w, DQuaternion actual, double eps, String msg
    ) {
        assertEquals(x, actual.x, eps, msg + " (x); actual=" + actual);
        assertEquals(y, actual.y, eps, msg + " (y); actual=" + actual);
        assertEquals(z, actual.z, eps, msg + " (z); actual=" + actual);
        assertEquals(w, actual.w, eps, msg + " (w); actual=" + actual);
    }

    // ---------------------------------------------------------------- rotation semantics

    @Test
    void rotateIsActiveRightHandedRotation() {
        // Right-hand rule about +Y by +90°: x̂ → -ẑ, ẑ → x̂, ŷ fixed.
        DQuaternion ry90 = DQuaternion.rotationByDegrees(new Vec3(0, 1, 0), 90);
        assertVec(new Vec3(0, 0, -1), ry90.rotate(new Vec3(1, 0, 0)), EPS,
            "+90° about +Y must map x̂ to -ẑ (active, right-handed)");
        assertVec(new Vec3(1, 0, 0), ry90.rotate(new Vec3(0, 0, 1)), EPS,
            "+90° about +Y must map ẑ to x̂");
        assertVec(new Vec3(0, 1, 0), ry90.rotate(new Vec3(0, 1, 0)), EPS,
            "the rotation axis is fixed");
    }

    @Test
    void rotationByDegreesNormalizesAxisAndMatchesHandComputedComponents() {
        // q = (axis*sin(θ/2), cos(θ/2)); for θ=90° about ŷ: (0, sin45°, 0, cos45°).
        DQuaternion q = DQuaternion.rotationByDegrees(new Vec3(0, 1, 0), 90);
        assertQuatComponents(0, SIN45, 0, SIN45, q, EPS, "axis-angle components (cos45°=sin45°)");

        // A non-normalized axis input must produce the identical quaternion.
        DQuaternion q2 = DQuaternion.rotationByDegrees(new Vec3(0, 17.5, 0), 90);
        assertQuatComponents(q.x, q.y, q.z, q.w, q2, EPS, "axis is normalized internally");
    }

    // ------------------------------------------------------- multiplication order convention

    @Test
    void hamiltonProductMatchesHandComputedComponents() {
        // q1 = 90° about X = (s,0,0,c); q2 = 90° about Y = (0,s,0,c) with s = c = sqrt(2)/2.
        // Hamilton product q1⊗q2 by the standard formula (hand-expanded):
        //   x = w1*x2 + x1*w2 + y1*z2 - z1*y2 = 0    + s*c  + 0 - 0 = 1/2
        //   y = w1*y2 - x1*z2 + y1*w2 + z1*x2 = c*s  - 0    + 0 + 0 = 1/2
        //   z = w1*z2 + x1*y2 - y1*x2 + z1*w2 = 0    + s*s  - 0 + 0 = 1/2
        //   w = w1*w2 - x1*x2 - y1*y2 - z1*z2 = c*c  - 0    - 0 - 0 = 1/2
        // (1/2,1/2,1/2,1/2) is the 120° rotation about (1,1,1)/sqrt(3), which cycles x̂→ŷ→ẑ→x̂.
        DQuaternion q1 = DQuaternion.rotationByDegrees(new Vec3(1, 0, 0), 90);
        DQuaternion q2 = DQuaternion.rotationByDegrees(new Vec3(0, 1, 0), 90);
        DQuaternion product = q1.hamiltonProduct(q2);
        assertQuatComponents(0.5, 0.5, 0.5, 0.5, product, EPS, "hand-expanded Hamilton product");
        assertVec(new Vec3(0, 1, 0), product.rotate(new Vec3(1, 0, 0)), EPS,
            "the 120° (1,1,1) rotation cycles x̂ to ŷ");
    }

    @Test
    void hamiltonProductAppliesRightOperandFirst() {
        // a = 90° about X (ŷ→ẑ), b = 90° about Z (x̂→ŷ). These do NOT commute on x̂:
        //   b first, then a: x̂ →(b)→ ŷ →(a)→ ẑ
        //   a first, then b: x̂ →(a)→ x̂ →(b)→ ŷ
        // IP convention (DQuaternion.hamiltonProduct javadoc): a.hamiltonProduct(b)
        // = "firstly do b's rotation and then do a's" — so it must map x̂ to ẑ.
        DQuaternion a = DQuaternion.rotationByDegrees(new Vec3(1, 0, 0), 90);
        DQuaternion b = DQuaternion.rotationByDegrees(new Vec3(0, 0, 1), 90);

        assertVec(new Vec3(0, 0, 1), a.hamiltonProduct(b).rotate(new Vec3(1, 0, 0)), EPS,
            "a.hamiltonProduct(b) applies b FIRST, a second");
        assertVec(new Vec3(0, 1, 0), b.hamiltonProduct(a).rotate(new Vec3(1, 0, 0)), EPS,
            "b.hamiltonProduct(a) applies a FIRST, b second (order matters)");
    }

    @Test
    void combineAppliesThisFirst() {
        // a.combine(b) = "firstly apply this (a) and then other (b)" = b⊗a:
        //   x̂ →(a: 90° about X)→ x̂ →(b: 90° about Z)→ ŷ
        DQuaternion a = DQuaternion.rotationByDegrees(new Vec3(1, 0, 0), 90);
        DQuaternion b = DQuaternion.rotationByDegrees(new Vec3(0, 0, 1), 90);
        assertVec(new Vec3(0, 1, 0), a.combine(b).rotate(new Vec3(1, 0, 0)), EPS,
            "a.combine(b) applies a FIRST, b second");
    }

    // ------------------------------------------------------------------ inverse / identity

    @Test
    void conjugationInvertsRotation() {
        DQuaternion q = DQuaternion.rotationByDegrees(new Vec3(1, 2, 3), 73);
        Vec3 v = new Vec3(0.3, -1.7, 2.9);

        assertVec(v, q.getConjugated().rotate(q.rotate(v)), EPS,
            "rotate then inverse-rotate must be the identity on vectors");
        assertSameRotation(DQuaternion.identity, q.hamiltonProduct(q.getConjugated()), EPS,
            "q ⊗ q̄ must be the identity quaternion");
        assertSameRotation(DQuaternion.identity, q.getConjugated().hamiltonProduct(q), EPS,
            "q̄ ⊗ q must be the identity quaternion");
    }

    @Test
    void normalizationScalesToUnitLength() {
        // |(2,-4,4,8)| = sqrt(4+16+16+64) = sqrt(100) = 10 (exact), so the normalized
        // components are (0.2,-0.4,0.4,0.8).
        DQuaternion n = new DQuaternion(2, -4, 4, 8).getNormalized();
        assertQuatComponents(0.2, -0.4, 0.4, 0.8, n, 1e-15, "hand-scaled components");
        assertEquals(1.0, n.dotProduct(n), EPS, "normalized quaternion has unit 4D length");

        // IP's explicit zero-length fallback (logs an error, returns identity).
        DQuaternion zero = new DQuaternion(0, 0, 0, 0).getNormalized();
        assertQuatComponents(0, 0, 0, 1, zero, 0, "zero-length falls back to identity");
    }

    @Test
    void isValidChecksMagnitude() {
        DQuaternion q = DQuaternion.rotationByDegrees(new Vec3(0, 1, 0), 30);
        assertTrue(q.isValid(), "unit quaternion is valid");
        // |q*0.5|² = 0.25, which is not > 0.9.
        assertFalse(q.multiply(0.5).isValid(), "quarter-magnitude quaternion is invalid");
    }

    // ----------------------------------------------------------------- axis-angle round trip

    @Test
    void axisAngleRoundTrip() {
        // axis (2,-1,2) has length 3 (exact); normalized (2/3, -1/3, 2/3).
        DQuaternion q = DQuaternion.rotationByDegrees(new Vec3(2, -1, 2), 73);
        assertEquals(73, q.getRotatingAngleDegrees(), 1e-9, "angle recovered");
        assertVec(new Vec3(2.0 / 3, -1.0 / 3, 2.0 / 3), q.getRotatingAxis(), EPS,
            "axis recovered normalized");
    }

    // -------------------------------------------------- matrix bridge (JOML column-form pin)

    @Test
    void toMatrixIsColumnFormAndAgreesWithRotate() {
        DQuaternion q = DQuaternion.rotationByDegrees(new Vec3(1, 2, 2), 40);
        Matrix4f m = q.toMatrix();

        // JOML column-vector convention: transformDirection(v) computes M·v, which must be
        // the same active rotation as q.rotate(v). (Float path → EPS_F.)
        Vec3 v = new Vec3(0.4, -1.25, 2.5);
        Vector3f transformed = m.transformDirection(
            new Vector3f((float) v.x, (float) v.y, (float) v.z));
        Vec3 rotated = q.rotate(v);
        assertVec(rotated, new Vec3(transformed.x, transformed.y, transformed.z), EPS_F,
            "M·v (JOML transformDirection) must equal q.rotate(v)");

        // The matrix COLUMNS are the images of the basis vectors (column-form).
        Vector4f col0 = m.getColumn(0, new Vector4f());
        Vector4f col1 = m.getColumn(1, new Vector4f());
        Vector4f col2 = m.getColumn(2, new Vector4f());
        assertVec(q.rotate(new Vec3(1, 0, 0)), new Vec3(col0.x, col0.y, col0.z), EPS_F,
            "column 0 = rotated x̂");
        assertVec(q.rotate(new Vec3(0, 1, 0)), new Vec3(col1.x, col1.y, col1.z), EPS_F,
            "column 1 = rotated ŷ");
        assertVec(q.rotate(new Vec3(0, 0, 1)), new Vec3(col2.x, col2.y, col2.z), EPS_F,
            "column 2 = rotated ẑ");

        // The trap (FrontClipping class of bugs): reading the matrix in ROW form — i.e.
        // transposing — yields the INVERSE rotation, not the rotation.
        Vector3f transposed = new Matrix4f(m).transpose().transformDirection(
            new Vector3f((float) v.x, (float) v.y, (float) v.z));
        Vec3 inverseRotated = q.getConjugated().rotate(v);
        assertVec(inverseRotated, new Vec3(transposed.x, transposed.y, transposed.z), EPS_F,
            "Mᵀ·v must be the INVERSE rotation — row-form misuse inverts the transform");
    }

    @Test
    void quatMatrixQuatRoundTripThroughJomlColumns() {
        // quat → float matrix → columns → matrixToQuaternion → same rotation.
        // matrixToQuaternion's vector args are the images of the basis vectors
        // (= the columns of the column-form matrix).
        DQuaternion q = DQuaternion.rotationByDegrees(new Vec3(3, -2, 5), 67.3);
        Matrix4f m = q.toMatrix();
        Vector4f c0 = m.getColumn(0, new Vector4f());
        Vector4f c1 = m.getColumn(1, new Vector4f());
        Vector4f c2 = m.getColumn(2, new Vector4f());
        DQuaternion back = DQuaternion.matrixToQuaternion(
            new Vec3(c0.x, c0.y, c0.z),
            new Vec3(c1.x, c1.y, c1.z),
            new Vec3(c2.x, c2.y, c2.z)
        );
        assertSameRotation(q, back, EPS_F, "quat→matrix→quat round trip (float bridge)");
    }

    @Test
    void matrixToQuaternionCoversAllShepperdBranches() {
        // Pure-double round trip via basis images q.getAxisW/H/getNormal (= matrix columns).
        // Branch selection in matrixToQuaternion is by trace/diagonal dominance:
        //   trace > 0            : any small rotation
        //   m00 dominant         : 180° about X, matrix diag (1,-1,-1), trace -1
        //   m11 dominant         : 180° about Y, matrix diag (-1,1,-1)
        //   m22 dominant         : 180° about Z, matrix diag (-1,-1,1)
        DQuaternion[] cases = {
            DQuaternion.rotationByDegrees(new Vec3(1, 1, 0), 20), // trace > 0
            new DQuaternion(1, 0, 0, 0),                          // 180° about X
            new DQuaternion(0, 1, 0, 0),                          // 180° about Y
            new DQuaternion(0, 0, 1, 0),                          // 180° about Z
        };
        for (DQuaternion q : cases) {
            DQuaternion back = DQuaternion.matrixToQuaternion(
                q.getAxisW(), q.getAxisH(), q.getNormal()
            );
            assertSameRotation(q, back, EPS, "basis-image round trip for " + q);
        }
    }

    @Test
    void basisImagesAndFromFacingVecs() {
        // +90° about Y: x̂→-ẑ, ŷ→ŷ, ẑ→x̂ (hand right-hand-rule values).
        DQuaternion ry90 = DQuaternion.rotationByDegrees(new Vec3(0, 1, 0), 90);
        assertVec(new Vec3(0, 0, -1), ry90.getAxisW(), EPS, "axisW = rotated x̂");
        assertVec(new Vec3(0, 1, 0), ry90.getAxisH(), EPS, "axisH = rotated ŷ");
        assertVec(new Vec3(1, 0, 0), ry90.getNormal(), EPS, "normal = rotated ẑ");

        // fromFacingVecs(W, H) must reconstruct the orientation (right-handed frame W,H,W×H).
        DQuaternion q = DQuaternion.rotationByDegrees(new Vec3(4, 1, -2), 123.4);
        DQuaternion back = DQuaternion.fromFacingVecs(q.getAxisW(), q.getAxisH());
        assertSameRotation(q, back, EPS, "fromFacingVecs recovers the orientation");
    }

    // ------------------------------------------------------------------- camera conventions

    @Test
    void cameraRotationMapsViewDirectionToNegativeZ() {
        // Analytically getCameraRotation(0,0) = Ry(180°): pitch term is identity and the yaw
        // term rotates 0+180 about ŷ. MC yaw 0 = facing +Z (south); the world-to-camera
        // rotation must map the view direction to OpenGL camera-forward -ẑ (Ry180: ẑ→-ẑ).
        DQuaternion q = DQuaternion.getCameraRotation(0, 0);
        assertVec(new Vec3(0, 0, -1), q.rotate(new Vec3(0, 0, 1)), EPS,
            "yaw 0 view direction (+Z) maps to camera -Z");
        // Closed form at (0,0): p=y=0 → (-sin0 sin0, cos0 cos0, sin0 cos0, -cos0 sin0) = (0,1,0,0).
        assertQuatComponents(0, 1, 0, 0, DQuaternion.getCameraRotation1(0, 0), EPS,
            "closed form at pitch=yaw=0 is the pure Ry(180°) quaternion");
    }

    @Test
    void cameraRotationClosedFormAgreesWithComposition() {
        // Hand-derivation that the two must agree (port-note S02-qmiscutil.md §4.3):
        // Rx(pitch) ⊗ Ry(yaw+180) with r2 = (0, cos y, 0, -sin y) (half-angle shift by 90°)
        // expands to exactly (-sin p sin y, cos p cos y, sin p cos y, -cos p sin y)
        // = getCameraRotation1. Verified here over a pitch×yaw grid including the poles.
        double[] pitches = {-90, -30, 0, 45.5, 90};
        double[] yaws = {-180, -77.7, 0, 30.25, 90, 179, 270};
        for (double pitch : pitches) {
            for (double yaw : yaws) {
                assertSameRotation(
                    DQuaternion.getCameraRotation(pitch, yaw),
                    DQuaternion.getCameraRotation1(pitch, yaw),
                    EPS,
                    "getCameraRotation vs closed form at pitch=" + pitch + " yaw=" + yaw
                );
            }
        }
    }

    @Test
    void pitchYawRoundTrip() {
        // Analytic inverse (hand-verified): with p=rad(pitch)/2, y=rad(yaw)/2 the closed-form
        // components give 2(Y²+Z²)-1 = cos(yaw), -2(XZ+YW) = sin(yaw),
        // 1-2(X²+Z²) = cos(pitch), 2(XW+YZ) = sin(pitch) — so atan2 recovers both exactly.
        double[][] cases = {{30, 45}, {-60, -120}, {0, 179}, {89, -179}};
        for (double[] c : cases) {
            DQuaternion q = DQuaternion.getCameraRotation1(c[0], c[1]);
            Pair<Double, Double> pitchYaw = DQuaternion.getPitchYawFromRotation(q);
            assertEquals(c[0], pitchYaw.getFirst(), 1e-9, "pitch recovered for " + c[0] + "/" + c[1]);
            assertEquals(c[1], pitchYaw.getSecond(), 1e-9, "yaw recovered for " + c[0] + "/" + c[1]);
        }
    }

    // ------------------------------------------------------------------------- interpolation

    @Test
    void interpolateSlerpHalfwayBetweenSameAxisRotationsHalvesTheAngle() {
        // slerp(identity, Ry(90°), 0.5) = Ry(45°) = (0, sin22.5°, 0, cos22.5°).
        // dot = cos45° ≈ 0.707 < 0.9995, so this exercises the true slerp branch.
        DQuaternion a = DQuaternion.identity;
        DQuaternion b = DQuaternion.rotationByDegrees(new Vec3(0, 1, 0), 90);
        DQuaternion mid = DQuaternion.interpolate(a, b, 0.5);
        assertQuatComponents(0, SIN22_5, 0, COS22_5, mid, EPS, "slerp midpoint = Ry(45°)");

        // Endpoints reproduce the inputs (s0=1,s1=0 at t=0; s0=0,s1=1 at t=1).
        assertQuatComponents(a.x, a.y, a.z, a.w, DQuaternion.interpolate(a, b, 0), EPS, "t=0 is a");
        assertQuatComponents(b.x, b.y, b.z, b.w, DQuaternion.interpolate(a, b, 1), EPS, "t=1 is b");
    }

    @Test
    void interpolateNlerpBranchForCloseInputs() {
        // dot = cos(0.5°) ≈ 0.99996 > 0.9995 → the nlerp fast path. For the exact midpoint of
        // two unit quaternions on the same great circle, normalize(a+b) IS the true midpoint:
        // Ry(0.5°) = (0, sin0.25°, 0, cos0.25°).
        DQuaternion a = DQuaternion.identity;
        DQuaternion b = DQuaternion.rotationByDegrees(new Vec3(0, 1, 0), 1);
        DQuaternion mid = DQuaternion.interpolate(a, b, 0.5);
        assertQuatComponents(
            0, Math.sin(Math.toRadians(0.25)), 0, Math.cos(Math.toRadians(0.25)),
            mid, EPS, "nlerp midpoint = Ry(0.5°)"
        );
    }

    @Test
    void interpolateHandlesDoubleCover() {
        // b and -b are the same rotation; interpolate must flip the sign (dot < 0 branch)
        // and still land on the Ry(45°) rotation at t=0.5.
        DQuaternion a = DQuaternion.identity;
        DQuaternion bNegated = DQuaternion.rotationByDegrees(new Vec3(0, 1, 0), 90).multiply(-1);
        DQuaternion mid = DQuaternion.interpolate(a, bNegated, 0.5);
        assertSameRotation(
            new DQuaternion(0, SIN22_5, 0, COS22_5), mid, EPS,
            "midpoint through the antipodal representative is still Ry(45°)"
        );
    }

    // ------------------------------------------------------------------- rotation between

    @Test
    void getRotationBetweenPerpendicularAndOblique() {
        // x̂ → ŷ: axis = x̂×ŷ = ẑ, angle 90° → (0, 0, sin45°, cos45°).
        DQuaternion q = DQuaternion.getRotationBetween(new Vec3(1, 0, 0), new Vec3(0, 1, 0));
        assertQuatComponents(0, 0, SIN45, SIN45, q, EPS, "90° about ẑ");
        assertVec(new Vec3(0, 1, 0), q.rotate(new Vec3(1, 0, 0)), EPS, "maps from onto to");

        // x̂ → (1,1,0)/sqrt(2): axis ẑ, angle 45° → (0, 0, sin22.5°, cos22.5°).
        DQuaternion q2 = DQuaternion.getRotationBetween(new Vec3(1, 0, 0), new Vec3(1, 1, 0));
        assertQuatComponents(0, 0, SIN22_5, COS22_5, q2, EPS, "45° about ẑ");
        assertVec(new Vec3(SIN45, SIN45, 0), q2.rotate(new Vec3(1, 0, 0)), EPS,
            "maps from onto normalized to");
    }

    // --------------------------------------------------------------------------- NBT bridge

    @Test
    void nbtRoundTripAndFallbacks() {
        // Round trip: put/get of doubles is exact.
        DQuaternion q = new DQuaternion(0.1, -0.2, 0.3, 0.9);
        DQuaternion back = DQuaternion.fromTag(q.toTag());
        assertQuatComponents(0.1, -0.2, 0.3, 0.9, back, 0, "NBT round trip is exact");

        // Non-compound tag → identity (IP fallback).
        assertQuatComponents(0, 0, 0, 1, DQuaternion.fromTag(DoubleTag.valueOf(1.0)), 0,
            "non-compound tag falls back to identity");

        // Compound without "x" → identity (IP's contains-guard fallback).
        assertQuatComponents(0, 0, 0, 1, DQuaternion.fromTag(new CompoundTag()), 0,
            "empty compound falls back to identity");

        // Compound WITH "x" but missing y/z/w: the 26.2 getDoubleOr(…, 0.0) translation must
        // reproduce IP 1.21.3's old getDouble missing-key default of 0.0 per key
        // (api-map q-misc-util C1; port-note S02-qmiscutil.md §2.3 hunk 4).
        CompoundTag partial = new CompoundTag();
        partial.putDouble("x", 0.5);
        assertQuatComponents(0.5, 0, 0, 0, DQuaternion.fromTag(partial), 0,
            "missing keys default to 0.0 exactly as IP's old getDouble");
    }

    // ------------------------------------------------------------- error snapping / alignment

    @Test
    void fixFloatingPointErrorAccumulationSnapsNearAxisValues() {
        // All four components are within the 1e-7 snap threshold of {0, 1}:
        // (1e-9, -1e-8, 5e-9, 1+3e-8) → (0, 0, 0, 1), then normalization keeps it exact.
        DQuaternion drifted = new DQuaternion(1e-9, -1e-8, 5e-9, 1 + 3e-8);
        DQuaternion fixed = drifted.fixFloatingPointErrorAccumulation();
        assertQuatComponents(0, 0, 0, 1, fixed, 0, "drifted identity snaps to exact identity");

        // A rotation whose components are far from {0,±1} must pass through unchanged
        // (up to re-normalization): 90° about Y has components ±sin45°.
        DQuaternion ry90 = DQuaternion.rotationByDegrees(new Vec3(0, 1, 0), 90);
        DQuaternion fixedRy90 = ry90.fixFloatingPointErrorAccumulation();
        assertQuatComponents(0, SIN45, 0, SIN45, fixedRy90, 1e-15, "non-near values unchanged");
    }

    @Test
    void isAxisAlignedChecksExactComponents() {
        assertTrue(DQuaternion.identity.isAxisAligned(), "identity is axis-aligned");
        assertTrue(new DQuaternion(1, 0, 0, 0).isAxisAligned(), "180° about X is axis-aligned");
        assertTrue(new DQuaternion(0, 0, 0, -1).isAxisAligned(), "negative identity is axis-aligned");
        assertFalse(DQuaternion.rotationByDegrees(new Vec3(0, 1, 0), 90).isAxisAligned(),
            "sin45° components are not axis-aligned");
    }

    // ------------------------------------------------------------------- distance / closeness

    @Test
    void distanceSqAndIsCloseHandleDoubleCover() {
        DQuaternion q = DQuaternion.rotationByDegrees(new Vec3(1, 2, 3), 73);
        assertEquals(0, DQuaternion.distanceSq(q, q.multiply(-1)), 0,
            "q and -q are the same rotation → distance 0");
        assertTrue(DQuaternion.isClose(q, q.multiply(-1)), "isClose across the double cover");

        // Hand value: distanceSq(identity, Ry90) = min(v1, v2) with
        // v1 = (sin45)² + (1-cos45)² = 2 - 2cos45° = 2 - sqrt(2); v2 = 2 + sqrt(2) → 2 - sqrt(2).
        DQuaternion ry90 = DQuaternion.rotationByDegrees(new Vec3(0, 1, 0), 90);
        assertEquals(2 - Math.sqrt(2), DQuaternion.distanceSq(DQuaternion.identity, ry90), EPS,
            "hand-computed distanceSq");
        assertFalse(DQuaternion.isClose(DQuaternion.identity, ry90),
            "distinct rotations are not close");
    }

    // ------------------------------------------------------------------------- euler bridge

    @Test
    void eulerAngleAxisConventions() {
        // IP convention (ported bit-for-bit, port-note S02-qmiscutil.md §4.3): fromEulerAngle applies
        // rotZ(roll) · rotY(-yaw) · rotX(pitch) — note the NEGATED yaw (MC yaw is
        // left-handed about +Y). Float path → EPS_F.
        // pitch 90: rotX(90°) maps ŷ→ẑ.
        assertVec(new Vec3(0, 0, 1),
            DQuaternion.fromEulerAngle(new Vec3(90, 0, 0)).rotate(new Vec3(0, 1, 0)), EPS_F,
            "pitch is right-handed about +X");
        // yaw 90 → rotY(-90°) maps x̂→ẑ (right-handed +90° about Y would map x̂→-ẑ).
        assertVec(new Vec3(0, 0, 1),
            DQuaternion.fromEulerAngle(new Vec3(0, 90, 0)).rotate(new Vec3(1, 0, 0)), EPS_F,
            "yaw is NEGATED (left-handed about +Y)");
        // roll 90: rotZ(90°) maps x̂→ŷ.
        assertVec(new Vec3(0, 1, 0),
            DQuaternion.fromEulerAngle(new Vec3(0, 0, 90)).rotate(new Vec3(1, 0, 0)), EPS_F,
            "roll is right-handed about +Z");
    }

    @Test
    void eulerAngleRoundTrip() {
        // fromEulerAngle builds Z·Y·X in exactly the order getEulerAnglesZYX decomposes,
        // and toEulerAngle un-negates the yaw — round trip within float precision for a
        // gimbal-safe angle triple.
        Vec3 euler = new Vec3(20, -35, 40);
        Vec3 back = DQuaternion.fromEulerAngle(euler).toEulerAngle();
        assertVec(euler, back, 1e-4, "euler round trip (pitch, yaw, roll degrees)");
    }

    // ------------------------------------------------------------------------ JOML bridge

    @Test
    void mcQuaternionBridgeCopiesComponents() {
        DQuaternion q = new DQuaternion(0.5, -0.5, 0.5, 0.5);
        org.joml.Quaternionf mc = q.toMcQuaternion();
        assertEquals(0.5f, mc.x, 0, "x");
        assertEquals(-0.5f, mc.y, 0, "y");
        assertEquals(0.5f, mc.z, 0, "z");
        assertEquals(0.5f, mc.w, 0, "w");

        DQuaternion fromDouble = DQuaternion.fromMcQuaternion(
            new org.joml.Quaterniond(0.1, 0.2, 0.3, 0.9));
        assertQuatComponents(0.1, 0.2, 0.3, 0.9, fromDouble, 0, "Quaterniond copies exactly");
    }
}
