package qouteall.q_misc_util.my_util;

import net.minecraft.world.phys.Vec3;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * AUTHORED S2 migration payload — NOT a carried IP test file (IP's test tree contains only
 * Mesh2DTest/HelperTest). Invariant tests for the carved-in {@link Plane}
 * (migration/EXECUTION_PLAN.md §3 S2(a) deliverable, hard constraint 8; D4.5 math harness —
 * the geometry-sign regression net, DEPENDENCY_ORDER §4.1 milestone 1).
 *
 * <p>Every expected value is hand-derived from first principles (derivations inline) —
 * never generated by calling the code under test.
 *
 * <p>Conventions pinned (cross-reference: migration/port-notes/S02-qmiscutil.md §4.8
 * "Plane / GeometryUtil / QuadTree / Range / Sphere", the merged mathA translator fragment's
 * "Plane normal-side convention"): the canonical constructor NORMALIZES the normal; signed
 * distance = normal · (p − pos); the "positive side" is the side the normal points to,
 * tested STRICTLY (&gt; 0); rayTraceGetT returns NaN below the 1e-5 parallelism threshold;
 * rayTrace rejects t &lt; 0; intersectionWithLineSegment requires t ∈ [0, 1] (closed);
 * clip-equation form n·p + W &gt; 0 with W = −normal·pos.
 */
class PlaneTest {

    private static final double EPS = 1e-12;

    private static void assertVec(Vec3 expected, Vec3 actual, double eps, String msg) {
        assertEquals(expected.x, actual.x, eps, msg + " (x); actual=" + actual);
        assertEquals(expected.y, actual.y, eps, msg + " (y); actual=" + actual);
        assertEquals(expected.z, actual.z, eps, msg + " (z); actual=" + actual);
    }

    // ------------------------------------------------------------ construction / normal form

    @Test
    void constructorNormalizesTheNormal() {
        // (0,2,0) has exact length 2 → stored normal must be exactly (0,1,0).
        Plane plane = new Plane(new Vec3(0, 5, 0), new Vec3(0, 2, 0));
        assertVec(new Vec3(0, 1, 0), plane.normal(), 0, "normal stored normalized");
        assertVec(new Vec3(0, 5, 0), plane.pos(), 0, "pos stored untouched");

        // Two planes built from different-length normals of the same direction are equal.
        assertEquals(
            new Plane(new Vec3(0, 5, 0), new Vec3(0, 3, 0)), plane,
            "equality is on the normalized form"
        );
        assertNotEquals(
            new Plane(new Vec3(0, 4, 0), new Vec3(0, 1, 0)), plane,
            "different pos is a different plane record"
        );
    }

    // -------------------------------------------------------------- signed distance / sides

    @Test
    void signedDistanceAndStrictPositiveSide() {
        // Plane y = 5 with normal +ŷ: distance is just (y - 5).
        Plane plane = new Plane(new Vec3(0, 5, 0), new Vec3(0, 1, 0));

        assertEquals(3, plane.getDistanceTo(new Vec3(3, 8, -2)), EPS, "above → +3");
        assertEquals(-3, plane.getDistanceTo(new Vec3(0, 2, 0)), EPS, "below → -3");
        assertEquals(0, plane.getDistanceTo(new Vec3(7, 5, 1)), EPS, "on the plane → 0");

        // The scalar overload must agree with the Vec3 overload.
        assertEquals(3, plane.getDistanceTo(3, 8, -2), EPS, "scalar overload above");
        assertEquals(-3, plane.getDistanceTo(0, 2, 0), EPS, "scalar overload below");

        assertTrue(plane.isPointOnPositiveSide(new Vec3(3, 8, -2)),
            "the positive side is where the normal points");
        assertFalse(plane.isPointOnPositiveSide(new Vec3(0, 2, 0)), "below is negative side");
        assertFalse(plane.isPointOnPositiveSide(new Vec3(7, 5, 1)),
            "on-plane is NOT positive (strict > 0)");
    }

    @Test
    void projectionAndReflection() {
        // Axis-aligned hand case, plane y = 5:
        Plane plane = new Plane(new Vec3(0, 5, 0), new Vec3(0, 1, 0));
        assertVec(new Vec3(3, 5, -2), plane.getProjection(new Vec3(3, 9, -2)), EPS,
            "projection drops the point onto the plane");
        assertVec(new Vec3(3, 1, -2), plane.getReflection(new Vec3(3, 9, -2)), EPS,
            "reflection mirrors across the plane");

        // Oblique hand case: plane through (1,1,1) with normal (1,1,1)/sqrt(3);
        // p = (2,3,4): p - pos = (1,2,3); distance = (1+2+3)/sqrt(3) = 2*sqrt(3);
        // projection = p - n*d = p - (1,1,1)*2 = (0,1,2); reflection = p - (1,1,1)*4 = (-2,-1,0).
        Plane oblique = new Plane(new Vec3(1, 1, 1), new Vec3(1, 1, 1));
        assertEquals(2 * Math.sqrt(3), oblique.getDistanceTo(new Vec3(2, 3, 4)), EPS,
            "hand-computed oblique distance");
        assertVec(new Vec3(0, 1, 2), oblique.getProjection(new Vec3(2, 3, 4)), EPS,
            "hand-computed oblique projection");
        assertVec(new Vec3(-2, -1, 0), oblique.getReflection(new Vec3(2, 3, 4)), EPS,
            "hand-computed oblique reflection");

        // Projection is idempotent and lands at distance 0.
        Vec3 projected = oblique.getProjection(new Vec3(2, 3, 4));
        assertEquals(0, oblique.getDistanceTo(projected), EPS, "projection lies on the plane");
        assertVec(projected, oblique.getProjection(projected), EPS, "projection is idempotent");
    }

    // ------------------------------------------------------------- move / opposite / parallel

    @Test
    void moveTranslatesAlongTheNormal() {
        Plane plane = new Plane(new Vec3(0, 5, 0), new Vec3(0, 1, 0));
        // move(+2): plane rises to y = 7 → distance from (0,8,0) shrinks from 3 to 1.
        assertEquals(1, plane.move(2).getDistanceTo(new Vec3(0, 8, 0)), EPS, "moved toward point");
        // move(-5): plane at y = 0.
        assertEquals(8, plane.move(-5).getDistanceTo(new Vec3(0, 8, 0)), EPS, "moved away");
    }

    @Test
    void oppositeFlipsSidesAndParallelKeepsNormal() {
        Plane plane = new Plane(new Vec3(0, 5, 0), new Vec3(0, 1, 0));

        Plane opposite = plane.getOpposite();
        assertVec(new Vec3(0, -1, 0), opposite.normal(), 0, "opposite normal is negated");
        assertVec(plane.pos(), opposite.pos(), 0, "opposite keeps pos");
        assertEquals(-3, opposite.getDistanceTo(new Vec3(3, 8, -2)), EPS, "distances negate");
        assertTrue(opposite.isPointOnPositiveSide(new Vec3(0, 2, 0)),
            "the below-point is on the opposite plane's positive side");

        Plane parallel = plane.getParallelPlane(new Vec3(9, 7, 3));
        assertVec(plane.normal(), parallel.normal(), 0, "parallel keeps the normal");
        assertEquals(0, parallel.getDistanceTo(new Vec3(9, 7, 3)), EPS,
            "parallel plane passes through the given pos");
        assertEquals(1, parallel.getDistanceTo(new Vec3(0, 8, 0)), EPS,
            "hand distance from the y=7 parallel plane");
    }

    // ------------------------------------------------------------------------- ray tracing

    @Test
    void rayTraceHitsMissesAndParallels() {
        // Plane y = 0 with normal +ŷ.
        Plane plane = new Plane(new Vec3(0, 0, 0), new Vec3(0, 1, 0));

        // Oblique hit: origin (1,4,2), vec (1,-2,0): t = -d(origin)/(n·vec) = -4/-2 = 2
        // → hit at origin + 2*vec = (3,0,2).
        assertEquals(2, plane.rayTraceGetT(new Vec3(1, 4, 2), new Vec3(1, -2, 0)), EPS,
            "hand-computed t");
        assertEquals(2, plane.rayTraceGetT(1, 4, 2, 1, -2, 0), EPS,
            "allocation-free overload agrees");
        Vec3 hit = plane.rayTrace(new Vec3(1, 4, 2), new Vec3(1, -2, 0));
        assertVec(new Vec3(3, 0, 2), hit, EPS, "hand-computed hit point");

        // Pointing away: t = -4/1 = -4 → rayTrace rejects (t < 0) but getT still reports it.
        assertEquals(-4, plane.rayTraceGetT(new Vec3(1, 4, 2), new Vec3(0, 1, 0)), EPS,
            "negative t reported by getT");
        assertNull(plane.rayTrace(new Vec3(1, 4, 2), new Vec3(0, 1, 0)),
            "ray pointing away from the plane misses");

        // Parallel: n·vec = 0 → NaN → null.
        assertTrue(Double.isNaN(plane.rayTraceGetT(new Vec3(1, 4, 2), new Vec3(1, 0, 0))),
            "parallel line has no t");
        assertNull(plane.rayTrace(new Vec3(1, 4, 2), new Vec3(1, 0, 0)), "parallel ray misses");
    }

    @Test
    void rayTraceParallelismThreshold() {
        Plane plane = new Plane(new Vec3(0, 0, 0), new Vec3(0, 1, 0));
        // |n·vec| below the hardcoded 1e-5 threshold → NaN. 2^-17 = 0.00000762939453125
        // is exactly representable and < 1e-5.
        assertTrue(
            Double.isNaN(plane.rayTraceGetT(new Vec3(1, 4, 2), new Vec3(1, 0.00000762939453125, 0))),
            "just-below-threshold slope is treated as parallel"
        );
        // 2^-5 = 0.03125 (exact) is above the threshold: t = -4/0.03125 = -128 exactly.
        assertEquals(-128, plane.rayTraceGetT(new Vec3(1, 4, 2), new Vec3(1, 0.03125, 0)), EPS,
            "above-threshold slope yields a finite t");
    }

    @Test
    void lineSegmentIntersectionIsClosedInterval() {
        Plane plane = new Plane(new Vec3(0, 0, 0), new Vec3(0, 1, 0));

        // Crossing segment: (1,-1,0) → (1,3,0): lineVec (0,4,0), t = 1/4 → (1,0,0).
        assertVec(new Vec3(1, 0, 0),
            plane.intersectionWithLineSegment(new Vec3(1, -1, 0), new Vec3(1, 3, 0)), EPS,
            "hand-computed crossing point");

        // Segment entirely above (t = -0.5 < 0) and entirely below (t = 1.25 > 1) → null.
        assertNull(plane.intersectionWithLineSegment(new Vec3(1, 1, 0), new Vec3(1, 3, 0)),
            "segment on one side does not intersect");
        assertNull(plane.intersectionWithLineSegment(new Vec3(1, -5, 0), new Vec3(1, -1, 0)),
            "segment stopping short does not intersect");

        // Endpoint exactly on the plane: (1,2,0) → (1,0,0): t = -2/-2 = 1 → INCLUSIVE.
        assertVec(new Vec3(1, 0, 0),
            plane.intersectionWithLineSegment(new Vec3(1, 2, 0), new Vec3(1, 0, 0)), EPS,
            "t = 1 endpoint touch counts (closed interval)");
    }

    // -------------------------------------------------------------------- clip equation form

    @Test
    void clipEquationCoefficientsMatchSignedDistance() {
        // Plane through (2,3,4) with raw normal (1,2,2), |.| = 3 → unit (1/3, 2/3, 2/3);
        // W = -n·pos = -(2/3 + 6/3·... ) = -(2 + 6 + 8)/3 = -16/3.
        Plane plane = new Plane(new Vec3(2, 3, 4), new Vec3(1, 2, 2));
        assertEquals(1.0 / 3, plane.getEquationX(), EPS, "unit normal x");
        assertEquals(2.0 / 3, plane.getEquationY(), EPS, "unit normal y");
        assertEquals(2.0 / 3, plane.getEquationZ(), EPS, "unit normal z");
        assertEquals(-16.0 / 3, plane.getEquationW(), EPS, "W = -normal·pos");

        // Because the normal is unit, n·p + W must equal the signed distance:
        // at the origin: 0 + W = -16/3 = getDistanceTo(0,0,0);
        // at (7,-1,2): (1*5 + 2*(-4) + 2*(-2))/3 = (5 - 8 - 4)/3 = -7/3.
        assertEquals(-16.0 / 3, plane.getDistanceTo(new Vec3(0, 0, 0)), EPS, "origin distance");
        double eq = plane.getEquationX() * 7 + plane.getEquationY() * -1
            + plane.getEquationZ() * 2 + plane.getEquationW();
        assertEquals(-7.0 / 3, eq, EPS, "equation value at (7,-1,2)");
        assertEquals(eq, plane.getDistanceTo(new Vec3(7, -1, 2)), EPS,
            "equation form equals signed distance for a unit normal");
    }

    // ------------------------------------------------------------------------ interpolation

    @Test
    void interpolateLerpsPosAndRenormalizesNormal() {
        Plane a = new Plane(new Vec3(0, 0, 0), new Vec3(1, 0, 0));
        Plane b = new Plane(new Vec3(2, 4, 6), new Vec3(0, 1, 0));

        Plane mid = Plane.interpolate(a, b, 0.5);
        assertVec(new Vec3(1, 2, 3), mid.pos(), EPS, "pos lerps componentwise");
        // lerp of the normals at 0.5 is (0.5, 0.5, 0) → renormalized (sqrt(2)/2, sqrt(2)/2, 0).
        assertVec(new Vec3(Math.sqrt(2) / 2, Math.sqrt(2) / 2, 0), mid.normal(), EPS,
            "normal lerp is renormalized");

        assertVec(a.pos(), Plane.interpolate(a, b, 0).pos(), EPS, "progress 0 pos = a");
        assertVec(a.normal(), Plane.interpolate(a, b, 0).normal(), EPS, "progress 0 normal = a");
        assertVec(b.pos(), Plane.interpolate(a, b, 1).pos(), EPS, "progress 1 pos = b");
        assertVec(b.normal(), Plane.interpolate(a, b, 1).normal(), EPS, "progress 1 normal = b");
    }

    // ------------------------------------------------- transformation coherence (DQuaternion)

    @Test
    void rotatingPlaneAndPointsPreservesSignedDistances() {
        // Rotations are isometries and preserve dot products, so building the rotated plane
        // from the rotated pos/normal must preserve every signed distance:
        //   n' · (q(p) - q(pos)) = q(n) · q(p - pos) = n · (p - pos).
        // Plane has no transform method of its own — the constructor composition IS the API
        // the portal code uses (rotate pos and normal, rebuild).
        Plane plane = new Plane(new Vec3(2, 3, 4), new Vec3(1, 2, 2));
        DQuaternion q = DQuaternion.rotationByDegrees(new Vec3(2, -1, 2), 40);

        Plane rotated = new Plane(q.rotate(plane.pos()), q.rotate(plane.normal()));

        Vec3[] points = {
            new Vec3(7, -1, 2),   // negative side (distance -7/3, see clip-equation test)
            new Vec3(0, 0, 0),    // negative side (distance -16/3)
            new Vec3(4, 2, 4),    // ON the plane: (2,-1,0)·(1,2,2) = 0
            new Vec3(3, 5, 6),    // positive side: (1,2,2)·(1,2,2)/3 = 9/3 = 3
        };
        for (Vec3 p : points) {
            assertEquals(
                plane.getDistanceTo(p),
                rotated.getDistanceTo(q.rotate(p)),
                EPS,
                "signed distance invariant under rotation for " + p
            );
            // Strict-side classification is only stable for points OFF the plane (the
            // on-plane point's rotated distance is ±1ulp noise around 0, sign arbitrary).
            if (Math.abs(plane.getDistanceTo(p)) > 1e-9) {
                assertEquals(
                    plane.isPointOnPositiveSide(p),
                    rotated.isPointOnPositiveSide(q.rotate(p)),
                    "side classification invariant under rotation for " + p
                );
            }
        }

        // The rotated normal stays unit length (constructor re-normalizes a unit vector
        // to itself), so the clip-equation form stays a signed distance too.
        assertEquals(1, rotated.normal().length(), EPS, "rotated normal is unit");
    }
}
